### ISSUE TITLE
Count unicode characters as length = 1

### ISSUE THREAD

**Issue by hackergrrl** [hackergrrl/txt-blit#1]
Right now there's some weird character counting going on..

**Comment by cblgh** [comment]
i wasn't sure if understood this correctly, but i had a try at fixing it using sindre's [string-width](https://github.com/sindresorhus/string-width). `string-width` does what `strlenAnsi(str)` does currently, except a bit more?

see https://github.com/cblgh/txt-blit/commit/67bc5d06b4dbf3994fe73a860fda83d0d1b08640

i tested it and it still doesn't fix emojis breaking the space counting though, so it's not an entire solution :(
let me know if you want me to create a PR, or if it just adds unnecessary deps to txt-blit

**Comment by hackergrrl** [comment]
Unless string-width is fixing something that's broken, I'm OK with holding off on adding it as a dep.
